title: '#xx タイトル'
labels: []
body:
  - type: textarea
    id: body
    attributes:
      label: Body
      description: 'body'
      value: |
        YouTube: {{URL}}
        connpass: {{URL}}

        <!-- サムネイル --->

        ----

        ## アジェンダ

        - TODO
